### ISSUE TITLE
docker pull hothamandcheese/firefly-gone-plaid:latest yields no results

### ISSUE THREAD

**Issue by JackPala** [sa7mon/firefly-gone-plaid#2]
docker pull hothamandcheese/firefly-gone-plaid:latest

image is not on dockerhub

**Comment by sa7mon** [comment]
Oops. Yeah, Docker Hub just changed their ToS so now they delete images that aren't pulled recently. I'll push an update to the code and readme with instructions to build it.

**Comment by sa7mon** [comment]
Okay, readme is updated.
